export const API_ENDPOINTS_AUTH_BASE = "/api/auth";
export const API_ENDPOINTS_MANAGE_DATA_BASE = "/api/datenpflege";
export const API_ENDPOINTS_METADATA_BASE = "/metadata";
export const API_ENDPOINTS_SHOWCASES_BASE = "/showcases";

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: `${API_ENDPOINTS_AUTH_BASE}/login`,
    LOGOUT: `${API_ENDPOINTS_AUTH_BASE}/logout`,
    CALLBACK: `${API_ENDPOINTS_AUTH_BASE}/callback`,
  },
  METADATA: {
    DELETE: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_METADATA_BASE}/delete`,
    CREATE: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_METADATA_BASE}/create`,
    EDIT: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_METADATA_BASE}/edit`,
    FETCH_FILE: (metadataName: string) =>
      `/api${API_ENDPOINTS_METADATA_BASE}/${metadataName}`,
  },
  SHOWCASES: {
    DELETE: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_SHOWCASES_BASE}/delete`,
    CREATE: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_SHOWCASES_BASE}/create`,
    EDIT: `${API_ENDPOINTS_MANAGE_DATA_BASE}${API_ENDPOINTS_SHOWCASES_BASE}/edit`,
  },
};
